# Generated by Django 6.0.6 on 2026-06-05 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('didactico', 'Material didáctico'), ('juguetes', 'Juguetes'), ('limpieza', 'Limpieza e higiene'), ('mobiliario', 'Mobiliario'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad', models.CharField(help_text='Ej: unidades, cajas, litros', max_length=50)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=1, help_text='Alerta cuando stock baje de este valor')),
                ('activo', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Item de inventario',
                'verbose_name_plural': 'Inventario',
                'ordering': ['sucursal', 'categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (compra/donación)'), ('salida', 'Salida (uso/pérdida)'), ('ajuste', 'Ajuste de inventario')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=300)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.iteminventario')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
