# Generated by Django 5.1.15 on 2026-10-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-fecha', '-created_at'], 'verbose_name': 'Movimiento de inventario'},
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_anterior',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_resultante',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=1, help_text='Se avisa cuando el stock sea igual o menor a este valor'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.PositiveIntegerField(help_text='Entrada/salida: unidades que se mueven. Ajuste: nuevo stock total'),
        ),
    ]
