# Generated by Django 6.0.6 on 2026-06-05 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ciudad', models.CharField(default='La Paz', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('directora', models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['directora', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('edad_min_meses', models.PositiveSmallIntegerField(help_text='Edad mínima en meses')),
                ('edad_max_meses', models.PositiveSmallIntegerField(help_text='Edad máxima en meses')),
                ('capacidad_maxima', models.PositiveSmallIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['sucursal', 'edad_min_meses'],
                'unique_together': {('sucursal', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('manana', 'Turno mañana'), ('tarde', 'Turno tarde'), ('completo', 'Turno completo (mañana y tarde)'), ('especial', 'Turno especial')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('costo_mensual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_diario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='core.sala')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['sala', 'hora_inicio'],
                'unique_together': {('sala', 'nombre')},
            },
        ),
    ]
