# Generated by Django 6.0.6 on 2026-06-05 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('ninos', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motivo', models.TextField(help_text='Señales o comportamientos observados')),
                ('area_derivacion', models.CharField(help_text='Ej: Terapia del lenguaje, psicología', max_length=200)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('aceptada', 'Aceptada por el centro'), ('en_proceso', 'En proceso de atención'), ('cerrada', 'Cerrada')], default='solicitada', max_length=20)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('respuesta_centro', models.TextField(blank=True)),
                ('consentimiento_tutor', models.BooleanField(default=False)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones', to='ninos.nino')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
            options={
                'verbose_name': 'Derivación al Centro Misael',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='PlanTrabajoMisael',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesional_email', models.EmailField(help_text='Email del profesional en el Centro Misael', max_length=254)),
                ('profesional_nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('consentimiento_tutor', models.BooleanField(default=False, help_text='El tutor autorizó compartir información entre ambos centros')),
                ('derivacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misael_link.derivacion')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_misael', to='ninos.nino')),
                ('plan_individual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_misael', to='agenda.planindividual')),
            ],
            options={
                'verbose_name': 'Plan de trabajo Centro Misael',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
