# Generated by Django 5.1.15 on 2026-08-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misael_link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantrabajomisael',
            name='area_intervencion',
            field=models.CharField(blank=True, help_text='Ej: Lenguaje, Terapia ocupacional, Psicología...', max_length=150),
        ),
        migrations.AddField(
            model_name='plantrabajomisael',
            name='frecuencia_sesiones',
            field=models.CharField(blank=True, help_text='Ej: 2 veces por semana', max_length=100),
        ),
        migrations.AddField(
            model_name='plantrabajomisael',
            name='informe_pdf',
            field=models.FileField(blank=True, help_text='Informe o plan de trabajo del Centro Misael, en PDF', null=True, upload_to='planes_misael/'),
        ),
        migrations.AddField(
            model_name='plantrabajomisael',
            name='notas_seguimiento',
            field=models.TextField(blank=True, help_text='Avances, observaciones de la educadora, ajustes acordados con el profesional'),
        ),
        migrations.AddField(
            model_name='plantrabajomisael',
            name='profesional_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='plantrabajomisael',
            name='proxima_revision',
            field=models.DateField(blank=True, help_text='Cuándo toca revisar/renovar el plan con el Centro Misael', null=True),
        ),
        migrations.AlterField(
            model_name='plantrabajomisael',
            name='descripcion',
            field=models.TextField(help_text='Objetivos y lineamientos del plan'),
        ),
    ]
