# Generated by Django 5.1.15 on 2026-08-12 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misael_link', '0004_delete_plantrabajomisael_and_more'),
        ('personal', '0003_personal_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivacion',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, help_text='Quién de Misael Kids solicitó la derivación. Puede quedar vacío si el usuario no tiene una ficha de Personal asociada — la derivación de todos modos puede crearla cualquier cuenta con permiso.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.personal'),
        ),
    ]
