# Generated by Django 6.0.6 on 2026-06-05 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ninos', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanIndividual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origen', models.CharField(choices=[('educadora', 'Creado por educadora'), ('centro_misael', 'Plan del Centro Misael')], default='educadora', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_individuales', to='ninos.nino')),
            ],
            options={
                'verbose_name': 'Plan individual',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoIndividual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField()),
                ('area', models.CharField(choices=[('motricidad_fina', 'Motricidad fina'), ('motricidad_gruesa', 'Motricidad gruesa'), ('lenguaje', 'Lenguaje y comunicación'), ('social', 'Desarrollo social'), ('cognitivo', 'Desarrollo cognitivo'), ('autonomia', 'Autonomía')], max_length=25)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('logrado', 'Logrado')], default='pendiente', max_length=15)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='agenda.planindividual')),
            ],
            options={
                'verbose_name': 'Objetivo individual',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionGrupal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('actividades', models.TextField()),
                ('areas_trabajadas', models.CharField(blank=True, help_text='Áreas de desarrollo abordadas', max_length=500)),
                ('observaciones', models.TextField(blank=True)),
                ('visible_padres', models.BooleanField(default=True)),
                ('educadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sala')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turno')),
            ],
            options={
                'verbose_name': 'Planificación grupal',
                'ordering': ['-fecha'],
                'unique_together': {('sala', 'turno', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='RegistroObjetivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('resultado', models.CharField(choices=[('trabajado', 'Trabajado'), ('logrado', 'Logrado hoy'), ('no_trabajado', 'No trabajado')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('educadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='agenda.objetivoindividual')),
            ],
            options={
                'verbose_name': 'Registro de objetivo',
                'ordering': ['-fecha'],
                'unique_together': {('objetivo', 'fecha')},
            },
        ),
    ]
