# Generated by Django 5.1.15 on 2026-07-24 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('personal', '0002_alter_personal_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificaciongrupal',
            name='educadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='planindividual',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='registroobjetivo',
            name='educadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.personal'),
        ),
    ]
