# Generated by Django 6.0.6 on 2026-06-05 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ninos/')),
                ('alergias', models.TextField(blank=True, help_text='Alergias alimentarias o medicamentosas')),
                ('condiciones_medicas', models.TextField(blank=True, help_text='Condiciones de salud relevantes')),
                ('medicacion_habitual', models.TextField(blank=True)),
                ('tiene_plan_misael', models.BooleanField(default=False, help_text='Tiene plan de trabajo del Centro Misael')),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Niño',
                'verbose_name_plural': 'Niños',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato de inscripción'), ('partida_nacimiento', 'Partida de nacimiento'), ('carnet_vacunas', 'Carnet de vacunas'), ('informe_medico', 'Informe médico'), ('foto', 'Foto'), ('otro', 'Otro')], max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('verificado', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ninos.nino')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='PersonaAutorizada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('parentesco', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autorizados/')),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, help_text='Nulo = indefinida', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizados', to='ninos.nino')),
            ],
            options={
                'verbose_name': 'Persona autorizada',
                'verbose_name_plural': 'Personas autorizadas',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, verbose_name='CI/DNI')),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_alt', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('parentesco', models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('abuelo', 'Abuelo/a'), ('tutor_legal', 'Tutor legal'), ('otro', 'Otro')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='NinoTutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('puede_retirar', models.BooleanField(default=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='ninos.nino')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninos', to='ninos.tutor')),
            ],
            options={
                'verbose_name': 'Relación niño-tutor',
                'unique_together': {('nino', 'tutor')},
            },
        ),
    ]
