# Generated by Django 6.0.6 on 2026-06-05 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ninos', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitoDesarrollo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=300)),
                ('area', models.CharField(choices=[('motricidad_fina', 'Motricidad fina'), ('motricidad_gruesa', 'Motricidad gruesa'), ('lenguaje', 'Lenguaje y comunicación'), ('social', 'Desarrollo social'), ('cognitivo', 'Desarrollo cognitivo'), ('autonomia', 'Autonomía')], max_length=25)),
                ('edad_min_meses', models.PositiveSmallIntegerField()),
                ('edad_max_meses', models.PositiveSmallIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hito de desarrollo',
                'ordering': ['edad_min_meses', 'area'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionNino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('logrado', 'Logrado'), ('en_proceso', 'En proceso'), ('no_logrado', 'No logrado aún')], max_length=15)),
                ('observacion', models.TextField(blank=True)),
                ('alerta_rezago', models.BooleanField(default=False)),
                ('educadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='ninos.nino')),
                ('hito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.hitodesarrollo')),
            ],
            options={
                'verbose_name': 'Evaluación de desarrollo',
                'ordering': ['-fecha'],
                'unique_together': {('nino', 'hito', 'fecha')},
            },
        ),
    ]
