# Generated by Django 5.1.15 on 2026-09-30 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
        ('personal', '0005_personal_datos_propios_usuario_opcional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionnino',
            name='educadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to='personal.personal'),
        ),
    ]
