# Generated by Django 5.1.15 on 2026-07-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_username_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, help_text='El login (incluido /admin/) acepta email O nombre de usuario indistintamente.', max_length=254, null=True, unique=True, verbose_name='email o usuario'),
        ),
    ]
