# Generated by Django 5.1.15 on 2026-10-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rol_recepcionista'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tema',
            field=models.CharField(blank=True, default='', help_text='Tema visual elegido por esta persona (vacío = el de por defecto). Es personal: no afecta a otros usuarios.', max_length=30),
        ),
    ]
