# Generated by Django 6.0.6 on 2026-06-05 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente_justificado', 'Ausente justificado'), ('ausente', 'Ausente')], default='presente', max_length=25)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('entregado_por', models.CharField(blank=True, max_length=200)),
                ('retirado_por', models.CharField(blank=True, max_length=200)),
                ('retiro_autorizado', models.BooleanField(default=True)),
                ('obs_entrada', models.TextField(blank=True)),
                ('obs_salida', models.TextField(blank=True)),
                ('motivo_ausencia', models.TextField(blank=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='inscripciones.inscripcion')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha'],
                'unique_together': {('inscripcion', 'fecha')},
            },
        ),
    ]
