# Generated by Django 6.0.6 on 2026-06-05 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ninos', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenteSalud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(choices=[('accidente', 'Accidente'), ('enfermedad', 'Enfermedad'), ('sintoma', 'Síntoma observado'), ('medicacion', 'Medicación aplicada')], max_length=15)),
                ('descripcion', models.TextField()),
                ('accion_tomada', models.TextField()),
                ('notificado_tutor', models.BooleanField(default=False)),
                ('hora_notificacion', models.TimeField(blank=True, null=True)),
                ('requirio_atencion_medica', models.BooleanField(default=False)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_salud', to='ninos.nino')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Incidente de salud',
                'verbose_name_plural': 'Incidentes de salud',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
