# Generated by Django 5.1.15 on 2026-09-30 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_personal_datos_propios_usuario_opcional'),
        ('salud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentesalud',
            name='reportado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_reportados', to='personal.personal'),
        ),
    ]
