# Generated by Django 6.0.6 on 2026-06-05 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='CI/DNI')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('rol', models.CharField(choices=[('educadora', 'Educadora'), ('ayudante', 'Ayudante'), ('directora', 'Directora'), ('administrativo', 'Administrativo'), ('cocina', 'Cocina')], max_length=20)),
                ('especialidad', models.CharField(blank=True, max_length=200)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_personal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['usuario__apellidos'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionPersonal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Nulo = asignación vigente', null=True)),
                ('es_titular', models.BooleanField(default=True, help_text='Titular o sustituta')),
                ('activa', models.BooleanField(default=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sala')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turno')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Asignación de personal',
                'verbose_name_plural': 'Asignaciones de personal',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaPersonal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('permiso', 'Con permiso'), ('vacacion', 'Vacaciones'), ('enfermedad', 'Baja por enfermedad')], default='presente', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Asistencia del personal',
                'verbose_name_plural': 'Asistencias del personal',
                'ordering': ['-fecha'],
                'unique_together': {('personal', 'fecha', 'sucursal')},
            },
        ),
    ]
