# Generated by Django 5.1.15 on 2026-07-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='ci',
            field=models.CharField(max_length=20, unique=True, verbose_name='CI'),
        ),
    ]
