# Generated by Django 5.1.15 on 2026-08-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_personal_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='personal/'),
        ),
    ]
