# Generated by Django 6.0.6 on 2026-06-05 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ninos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modalidad_pago', models.CharField(choices=[('mensual', 'Mensualidad'), ('diaria', 'Por día')], default='mensual', max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('costo_mensual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_diario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tipo_ajuste', models.CharField(choices=[('ninguno', 'Sin ajuste'), ('descuento_porcentaje', 'Descuento en porcentaje'), ('descuento_monto', 'Descuento en monto fijo'), ('beca', 'Beca (sin costo)')], default='ninguno', max_length=25)),
                ('porcentaje_ajuste', models.DecimalField(decimal_places=2, default=0, help_text='Para tipo descuento_porcentaje: ej. 20.00 = 20%', max_digits=5)),
                ('monto_ajuste', models.DecimalField(decimal_places=2, default=0, help_text='Para tipo descuento_monto: monto fijo a descontar', max_digits=8)),
                ('motivo_ajuste', models.TextField(blank=True, help_text='Justificación del ajuste o beca')),
                ('activa', models.BooleanField(default=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='ninos.nino')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sala')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turno')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('mensualidad', 'Mensualidad'), ('diario', 'Cobro por día'), ('extra', 'Cobro extra')], max_length=15)),
                ('periodo', models.CharField(blank=True, help_text='Ej: 2025-06 para mensualidades', max_length=7)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('anulado', 'Anulado')], default='pendiente', max_length=15)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr', 'QR')], max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('observacion', models.TextField(blank=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='inscripciones.inscripcion')),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
