# Generated by Django 5.1.15 on 2026-07-25 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='inscripcion_origen',
            field=models.ForeignKey(blank=True, help_text='Inscripción anterior de la que proviene (si fue transferida).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias', to='inscripciones.inscripcion'),
        ),
    ]
