# Generated by Django 5.1.15 on 2026-07-25 18:51

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_inscripcion_inscripcion_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='monto_condonado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='cobro',
            name='motivo_condonacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cobro',
            name='periodo_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cobro',
            name='periodo_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago parcial'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('anulado', 'Anulado')], default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='periodo',
            field=models.CharField(blank=True, help_text='Etiqueta del período. Para mensualidades ancladas a la fecha de inscripción, ej: "2026-02-20 a 2026-03-20".', max_length=30),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr', 'QR')], default='efectivo', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('observacion', models.TextField(blank=True)),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inscripciones.cobro')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
    ]
