# Generated by Django 5.1.15 on 2026-07-31 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_cobro_monto_condonado_cobro_motivo_condonacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cobro',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'mensualidad')), fields=('inscripcion', 'tipo', 'periodo_inicio'), name='uniq_cobro_mensualidad_por_ciclo'),
        ),
        migrations.AddConstraint(
            model_name='cobro',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'diario')), fields=('inscripcion', 'tipo', 'periodo'), name='uniq_cobro_diario_por_dia'),
        ),
    ]
