# Generated by Django 5.1.15 on 2026-10-01 22:36

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0007_reparar_cobros_condonados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='dias_semana',
            field=models.JSONField(blank=True, default=list, help_text='Días de la semana en que asiste (0=lunes ... 6=domingo). Vacío = todos los días.'),
        ),
        migrations.CreateModel(
            name='AbonoDiario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr', 'QR')], default='efectivo', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('observacion', models.TextField(blank=True)),
                ('numero_recibo', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='inscripciones.inscripcion')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abono (por día)',
                'verbose_name_plural': 'Abonos (por día)',
                'ordering': ['fecha_pago', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='abono_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='inscripciones.abonodiario'),
        ),
        migrations.CreateModel(
            name='DiasContratados',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('inicial', 'Días iniciales'), ('ampliacion', 'Ampliación'), ('reduccion', 'Reducción')], max_length=12)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('nota', models.TextField(blank=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_contratados', to='inscripciones.inscripcion')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Días contratados',
                'verbose_name_plural': 'Días contratados',
                'ordering': ['fecha', 'created_at'],
            },
        ),
    ]
