# Generated by Django 5.1.15 on 2026-10-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0008_pago_por_dias_abonos_y_dias_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonodiario',
            name='es_traspaso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='a_cuenta',
            field=models.BooleanField(default=False),
        ),
    ]
