# Generated by Django 5.1.15 on 2026-10-02 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0009_saldo_a_cuenta_por_traspaso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abonodiario',
            name='devuelto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='inscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_saldo', to='inscripciones.inscripcion'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='cobro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='inscripciones.cobro'),
        ),
        migrations.AddConstraint(
            model_name='devolucion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cobro__isnull', False), ('inscripcion__isnull', True)), models.Q(('cobro__isnull', True), ('inscripcion__isnull', False)), _connector='OR'), name='devolucion_de_un_cobro_o_de_una_cuenta'),
        ),
    ]
