# Generated by Django 5.1.15 on 2026-10-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0010_devolucion_de_saldo_a_favor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='dias_programados',
            field=models.JSONField(blank=True, default=list, help_text='Fechas exactas (YYYY-MM-DD) en que asistirá. Solo modalidad por día.'),
        ),
    ]
